### ISSUE TITLE
ci-cmd delete fails when there are dashboards in creation failed state returned in the list dashboard operations

### ISSUE THREAD

**Issue by cristian-popa** [aws-samples/aws-cudos-framework-deployment#131]
cid-cmd delete

CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 1.0 Beta

Loading plugins...
        Core loaded
done

Checking AWS environment...
        accountId:XXXXXXXXXXX
        AWS userId: assumed-role/Admin/popcr-Isengard
        Region: us-east-2
done

Discovering deployed dashboards...  [######------------------------------]   16%  "test import" (test-import-2)
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/bin/cid-cmd", line 8, in <module>
    sys.exit(main())
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 53, in delete
    App.delete(dashboard_id=kwargs.get('dashboard_id'))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 309, in delete
    dashboard_id = self.qs.select_dashboard(force=True)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight.py", line 302, in select_dashboard
    for dashboard in self.dashboards.values():
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight.py", line 149, in dashboards
    self.discover_dashboards(self._resources.get('dashboards'))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight.py", line 206, in discover_dashboards
    res = next((sub for sub in supported_dashboards.values() if sub['templateId'] == dashboard.templateId), None)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight.py", line 206, in <genexpr>
    res = next((sub for sub in supported_dashboards.values() if sub['templateId'] == dashboard.templateId), None)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight.py", line 64, in templateId
    return str(self.version.get('SourceEntityArn').split('/')[1])
AttributeError: 'NoneType' object has no attribute 'split'

aws quicksight describe-dashboard --aws-account-id XXXXXXXXX --region us-east-2 --dashboard-id test-import-2
{
    "Status": 200,
    "Dashboard": {
        "DashboardId": "test-import-2",
        "Arn": "arn:aws:quicksight:us-east-2:XXXXXXXXX:dashboard/test-import-2",
        "Name": "test import",
        "Version": {
            "CreatedTime": "2021-03-10T18:27:44.919000+00:00",
            "Errors": [
                {
                    "Type": "VALIDATION_ERROR",
                    "Message": "Given placeholders [TestDS] are not part of template"
                }
            ],
            "VersionNumber": 1,
            "Status": "CREATION_FAILED",
            "DataSetArns": [],
            "Description": "1",
            "Sheets": []
        },
        "CreatedTime": "2021-03-10T18:27:44.044000+00:00",
        "LastPublishedTime": "2021-03-10T18:27:44.044000+00:00",
        "LastUpdatedTime": "2021-03-10T18:27:44.919000+00:00"
    },
    "RequestId": "a540ac21-d499-45bf-8e4c-d271d0c9c2ea"
}

**Comment by darken99** [comment]
Is this still relevant? I think it has to be fixed by some of the PRs

**Comment by iakov-aws** [comment]
Closing. please reopen if still relevant
