### ISSUE TITLE
deploy command fails consistently 

### ISSUE THREAD

**Issue by engrun** [aws-samples/aws-cudos-framework-deployment#292]
I've played around a bit with this tool, but reverted back to manual/CFN deployment options as the tool fails with

**Invalid type for parameter CatalogName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>**

However, I came back to this tool, due to the Compute Optimiser Dashboard only being available via `cid-cmd`. 

See below for error log

```
[cloudshell-user@ip-10-0-20-208 ~]$ cid-cmd -vv deploy
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.1.30 Beta

Logging level set to: DEBUG
Loading plugins...
        Core loaded


Checking AWS environment...
        profile name: default
        accountId: <my account id>
        AWS userId: <my user id>
        Region: eu-west-1



? [dashboard-id] Please select dashboard to install: [compute-optimizer-dashboard] Compute Optimizer Dashboard
Discovering deployed dashboards...  [####################################]  100%  "Trusted Advisor Organizational View" (ta-organiza          

Required datasets: 
 - compute_optimizer_all_options


Looking by DataSetId defined in template...complete

There are still 1 datasets missing: compute_optimizer_all_options
Creating dataset: compute_optimizer_all_options
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/bin/cid-cmd", line 8, in <module>
    sys.exit(main())
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 25, in wrapper
    res = func(ctx, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 102, in deploy
    ctx.obj.deploy(**kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 261, in deploy
    self.create_datasets(required_datasets, dashboard_datasets, recursive=recursive, update=update)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 824, in create_datasets
    if self.create_or_update_dataset(dataset_definition, dataset_id, recursive=recursive, update=update):
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 925, in create_or_update_dataset
    self.athena.discover_views(required_views)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/athena.py", line 349, in discover_views
    self.get_table_metadata(TableName=view_name)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/athena.py", line 179, in get_table_metadata
    'DatabaseName': self.DatabaseName,
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/athena.py", line 74, in DatabaseName
    athena_databases = self.list_databases()
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/athena.py", line 137, in list_databases
    return self.client.list_databases(CatalogName=self.CatalogName).get('DatabaseList')
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/botocore/client.py", line 875, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/botocore/client.py", line 936, in _convert_to_request_dict
    api_params, operation_model
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter CatalogName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
[cloudshell-user@ip-10-0-20-208 ~]$ 
```

**Comment by engrun** [comment]
Hi

Yes, output shows it is there
```{
    "DataCatalogsSummary": [
        {
            "CatalogName": "AwsDataCatalog",
            "Type": "GLUE"
        },
        {
            "CatalogName": "aws-config-snapshot",
            "Type": "GLUE"
        }
    ]
}
```

I also have run through the data collection lab, so that should be fine.  At least I can see a `rightsizing/` folder in the costoptimizationdata bucket

**Comment by iakov-aws** [comment]
There was a bug when we had multiple catalogs. Thanks for raising this
