### ISSUE TITLE
pip3 install --upgrade cid-cmd fails

### ISSUE THREAD

**Issue by engrun** [aws-samples/aws-cudos-framework-deployment#319]
Hi. 
with reference to issue  https://github.com/aws-samples/aws-cudos-framework-deployment/issues/292

is this actually fixed?  I see the issue is closed, however, I still get the same error, and the version of cid-cmd is `0.1.30 Beta`

What also happens is that the `pip3 install --upgrade cid-cmd` fails with the following stacktrace

```
[cloudshell-user@ip- ~]$ pip install --upgrade cid-cmd
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cid-cmd in ./.local/lib/python3.7/site-packages (0.1.30)
Requirement already satisfied: six>=1.15 in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.16.0)
Requirement already satisfied: questionary>=1.10 in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.10.0)
Requirement already satisfied: boto3>=1.19 in /usr/local/lib/python3.7/site-packages (from cid-cmd) (1.24.9)
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (from cid-cmd) (49.1.3)
Requirement already satisfied: Click>=8.0 in ./.local/lib/python3.7/site-packages (from cid-cmd) (8.1.3)
Requirement already satisfied: deepmerge in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.0.1)
Requirement already satisfied: PyYAML in /usr/local/lib64/python3.7/site-packages (from cid-cmd) (5.4.1)
Requirement already satisfied: yaspin==0.14.1 in ./.local/lib/python3.7/site-packages (from cid-cmd) (0.14.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from cid-cmd) (2.25.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/site-packages (from boto3>=1.19->cid-cmd) (0.6.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.7/site-packages (from boto3>=1.19->cid-cmd) (0.10.0)
Requirement already satisfied: botocore<1.28.0,>=1.27.9 in ./.local/lib/python3.7/site-packages (from boto3>=1.19->cid-cmd) (1.27.48)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/site-packages (from Click>=8.0->cid-cmd) (4.11.4)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in ./.local/lib/python3.7/site-packages (from questionary>=1.10->cid-cmd) (3.0.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (1.26.9)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (2022.5.18.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (2.10)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.7/site-packages (from botocore<1.28.0,>=1.27.9->boto3>=1.19->cid-cmd) (2.8.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt_toolkit<4.0,>=2.0->questionary>=1.10->cid-cmd) (0.1.9)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->Click>=8.0->cid-cmd) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->Click>=8.0->cid-cmd) (3.8.0)
--- Logging error ---
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/utils/entrypoints.py", line 60, in get_best_invocation_for_this_pip
    os.path.join(binary_prefix, exe_name),
  File "/usr/lib64/python3.7/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
  File "/home/cloudshell-user/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='22.2.2'),)
[cloudshell-user@~]$ 
```

**So if a fix is actually released, I'm not able to get it as the update command fails**

**Comment by darken99** [comment]
The error says you dont have `pip` binary. Make sure to install pip and use preferred command - `python3 -m pip install -U cid-cmd`

**Comment by engrun** [comment]
Using that command does not work either, same error. 
But running `sudo yum install pip` before upgrading cid-cmd solves it. 

*Documentation should probably be updated to reflect this.*

So thanks, works now
