### ISSUE TITLE
Dashboard is not deploying

### ISSUE THREAD

**Issue by milalima** [aws-samples/aws-cudos-framework-deployment#332]
Hey all, I am getting the following error when I am trying to deploy a Cudos Dashboard.
Can someone help me:

Looking by DataSetId defined in template...complete

There are still 5 datasets missing: compute_savings_plan_eligible_spend, customer_all, ec2_running_cost, s3_view, summary_view
Creating dataset: compute_savings_plan_eligible_spend
Traceback (most recent call last):
File "/opt/homebrew/bin/cid-cmd", line 8, in
sys.exit(main())
File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/cid/cli.py", line 25, in wrapper
res = func(ctx, **kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/cid/cli.py", line 105, in deploy
ctx.obj.deploy(**kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/cid/common.py", line 279, in deploy
self.create_datasets(required_datasets, dashboard_datasets, recursive=recursive, update=update)
File "/opt/homebrew/lib/python3.9/site-packages/cid/common.py", line 892, in create_datasets
if self.create_or_update_dataset(dataset_definition, dataset_id, recursive=recursive, update=update):
File "/opt/homebrew/lib/python3.9/site-packages/cid/common.py", line 961, in create_or_update_dataset
self.qs.create_data_source() # FIXME: we need to use name/id provided by user if any
File "/opt/homebrew/lib/python3.9/site-packages/cid/helpers/quicksight/init.py", line 204, in create_data_source
'user_arn': self.user.get('Arn')
File "/opt/homebrew/lib/python3.9/site-packages/cid/helpers/quicksight/init.py", line 89, in user
self._user = self.select_user()
File "/opt/homebrew/lib/python3.9/site-packages/cid/helpers/quicksight/init.py", line 417, in select_user
user_list = self.identityClient.list_users(AwsAccountId=self.account_id, Namespace='default').get('UserList')
File "/opt/homebrew/lib/python3.9/site-packages/botocore/client.py", line 508, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/homebrew/lib/python3.9/site-packages/botocore/client.py", line 915, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ListUsers operation: Namespace default not found in account XXXXXX. AWS account ID: XXXXXXXX, Namespace: default.

Logs is attached. 

[](url
[cid.log](https://github.com/aws-samples/aws-cudos-framework-deployment/files/9353848/cid.log)
)

**Comment by darken99** [comment]
Hello,
You need to enable QuickSight Enterprise Edition as mentioned in the [PREREQUISITES](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/)

**Comment by milalima** [comment]
Hello Darken, I am still with the issue. 

The logs show that I don't have QuickSight Enterprise but it is enabled:

![Screen Shot 2022-08-18 at 10 34 59](https://user-images.githubusercontent.com/48295637/185461336-948ebb3e-c9f8-4f67-a9eb-34a6e17e827a.png)
e:


2022-08-15 14:55:39,341 - INFO - cid.helpers.quicksight:describe_user:706 - QuickSight user AWSReservedSSO_account-admin_d1224ec0239942f5/milima@ea.com not found.
[cid.log](https://github.com/aws-samples/aws-cudos-framework-deployment/files/9376309/cid.log)

2022-08-15 14:55:39,448 - DEBUG - cid.common:create_datasets:902 - An error occurred (ResourceNotFoundException) when calling the ListUsers operation: Namespace default not found in account XXXXX. AWS account ID: XXXX, Namespace: default.

Logs attached
