### ISSUE TITLE
Error updating the DataTransfer Cost Analysis Dashboard

### ISSUE THREAD

**Issue by robmoss2k** [aws-samples/aws-cudos-framework-deployment#422]
When running `cid-cmd update`, I get the following error (account ID/profile/userId redacted):

```cid-cmd --profile 'my-aws-profile' --region_name 'us-east-1' update
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.2.6 Beta

Loading plugins...
        Core loaded


Checking AWS environment...
        profile name: my-aws-profile
        accountId: 123456789012
        AWS userId: my-username
        Region: us-east-1


Discovering deployed dashboards...  [#-----------------------------------]    3%  "Compute Savings" (0a5e8d7e-bf7e-404b-
Discovering deployed dashboards...  [##----------------------------------]    6%  "10M+ Team KPI - Excluding Spiky" (14a
Discovering deployed dashboards...  [###---------------------------------]   10%  "DataTransfer new dashboard" (19435ca9
Discovering deployed dashboards...  [####--------------------------------]   13%  00:00:06  "Test Dashboard" (1e2e70cd-8
Discovering deployed dashboards...  [######------------------------------]   17%  00:00:06  "Top 10 Account CR Spec" (31
Discovering deployed dashboards...  [#######-----------------------------]   20%  00:00:05  "Quaterly KPI and Drill Down
Discovering deployed dashboards...  [########----------------------------]   24%  00:00:05  "ESW Weekly Product Trends" 
Discovering deployed dashboards...  [#########---------------------------]   27%  00:00:05  "EC2 Daily Cost Analysis" (5
Discovering deployed dashboards...  [###########-------------------------]   31%  00:00:05  "Optimize RDS CL/CR Spec" (6
Discovering deployed dashboards...  [############------------------------]   34%  00:00:05  "Leaderboard to analyze hour
Discovering deployed dashboards...  [#############-----------------------]   37%  00:00:04  "Aurea AWS Cost Summary" (95
Discovering deployed dashboards...  [##############----------------------]   41%  00:00:04  "Contractor replacement" (98
Discovering deployed dashboards...  [################--------------------]   44%  00:00:04  "EC2 Spending" (9cebbef1-893
Discovering deployed dashboards...  [#################-------------------]   48%  00:00:04  "Cost deltas" (a2de5d6c-4010
Discovering deployed dashboards...  [##################------------------]   51%  00:00:03  "ESW Spend per week" (b1d4ba
Discovering deployed dashboards...  [###################-----------------]   55%  00:00:03  "Central RDS Dashboard - Cos
Discovering deployed dashboards...  [#####################---------------]   58%  00:00:03  "Compute Optimizer Dashboard
Discovering deployed dashboards...  [######################--------------]   62%  00:00:03  "Cost Intelligence Dashboard
Discovering deployed dashboards...  [#######################-------------]   65%  00:00:03  "CUDOS Dashboard" (cudos)   
Discovering deployed dashboards...  [########################------------]   68%  00:00:03  "DataTransfer Cost Analysis Dashboard" (data_trans
CRITICAL - Error: An error occurred (AccessDeniedException) when calling the DescribeTemplate operation: User: arn:aws:iam::123456789012:user/my-username is not authorized to perform: quicksight:DescribeTemplate on resource: arn:aws:quicksight:us-east-1:223485597511:template/data-transfer-cost-analysis-template/version/2 because no resource-based policy allows the quicksight:DescribeTemplate action - Cannot find data-transfer-cost-analysis-template in account 223485597511.
```

Issuing the following command gives this output (account ID/user ID/access key redacted):

```aws quicksight describe-dashboard --dashboard-id 'data-transfer-cost-analysis-template' --query 'Dashboard.Version.SourceEntityArn' --aws-account-id '223485597511' --debug
2022-12-06 08:25:24,355 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.9.4 Python/3.9.11 Windows/10 exe/AMD64
2022-12-06 08:25:24,355 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'describe-dashboard', '--dashboard-id', 'data-transfer-cost-analysis-template', '--query', 'Dashboard.Version.SourceEntityArn', '--aws-account-id', '223485597511', '--debug']
2022-12-06 08:25:24,392 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x0000013155F40790>
2022-12-06 08:25:24,392 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x0000013155D9D5E0>
2022-12-06 08:25:24,393 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-12-06 08:25:24,396 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000013155D33310>
2022-12-06 08:25:24,396 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x0000013155D3C430>
2022-12-06 08:25:24,396 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x0000013155F56160>
2022-12-06 08:25:24,396 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x0000013155DE71F0>
2022-12-06 08:25:24,397 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-12-06 08:25:24,397 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x0000013155F4C3A0>
2022-12-06 08:25:24,397 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000013155FE1580>>
2022-12-06 08:25:24,398 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2022-12-06 08:25:24,400 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x0000013155E97160>
2022-12-06 08:25:24,400 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x0000013155E97CA0>
2022-12-06 08:25:24,400 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x0000013155E97C10>
2022-12-06 08:25:24,400 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x0000013155E97DC0>
2022-12-06 08:25:24,401 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x0000013155E97D30>
2022-12-06 08:25:24,401 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x0000013155FF2040>
2022-12-06 08:25:24,401 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.9.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
2022-12-06 08:25:24,402 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['quicksight', 'describe-dashboard', '--dashboard-id', 'data-transfer-cost-analysis-template', '--query', 'Dashboard.Version.SourceEntityArn', '--aws-account-id', '223485597511', '--debug']
2022-12-06 08:25:24,402 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x0000013155F40DC0>
2022-12-06 08:25:24,402 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x0000013155938670>
2022-12-06 08:25:24,402 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x0000013155FB55E0>
2022-12-06 08:25:24,402 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x00000131559309D0>
2022-12-06 08:25:24,403 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x0000013155B3D5E0>
2022-12-06 08:25:24,404 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-12-06 08:25:24,405 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x0000013155DE70D0>
2022-12-06 08:25:24,405 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x0000013155D92310>
2022-12-06 08:25:24,443 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\quicksight\2018-04-01\service-2.json
2022-12-06 08:25:24,453 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight: calling handler <function add_waiters at 0x0000013155F4C3A0>
2022-12-06 08:25:24,489 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000013155FE1580>>
2022-12-06 08:25:24,489 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('aws-account-id', <awscli.arguments.CLIArgument object at 0x00000131560A42E0>), ('dashboard-id', <awscli.arguments.CLIArgument object at 0x00000131560A4310>), ('version-number', <awscli.arguments.CLIArgument object at 0x00000131560A4340>), ('alias-name', <awscli.arguments.CLIArgument object at 0x00000131560A4280>)])
2022-12-06 08:25:24,490 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_streaming_output_arg at 0x0000013155F450D0>
2022-12-06 08:25:24,490 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_cli_input_json at 0x0000013155B3DDC0>
2022-12-06 08:25:24,490 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_cli_input_yaml at 0x0000013155B47040>
2022-12-06 08:25:24,491 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function unify_paging_params at 0x0000013155D9DB80>
2022-12-06 08:25:24,529 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\quicksight\2018-04-01\paginators-1.json
2022-12-06 08:25:24,529 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\quicksight\2018-04-01\paginators-1.sdk-extras.json
2022-12-06 08:25:24,530 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.quicksight.describe-dashboard: calling handler <function add_generate_skeleton at 0x0000013155E8D700>
2022-12-06 08:25:24,530 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x00000131560A43A0>>
2022-12-06 08:25:24,531 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x00000131560A43D0>>
2022-12-06 08:25:24,531 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.quicksight.describe-dashboard: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x00000131560A45B0>>
2022-12-06 08:25:24,531 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight_describe-dashboard: calling handler <function add_waiters at 0x0000013155F4C3A0>
2022-12-06 08:25:24,531 - MainThread - botocore.hooks - DEBUG - Event building-command-table.quicksight_describe-dashboard: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x0000013155FE1580>>
2022-12-06 08:25:24,533 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.aws-account-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,533 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.quicksight.describe-dashboard: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000013155AE0AC0>
2022-12-06 08:25:24,534 - MainThread - awscli.arguments - DEBUG - Unpacked value of '223485597511' for parameter "aws_account_id": '223485597511'
2022-12-06 08:25:24,535 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.dashboard-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,535 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.quicksight.describe-dashboard: calling handler <awscli.argprocess.ParamShorthandParser object at 0x0000013155AE0AC0>
2022-12-06 08:25:24,535 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'data-transfer-cost-analysis-template' for parameter "dashboard_id": 'data-transfer-cost-analysis-template'
2022-12-06 08:25:24,535 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.version-number: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,536 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.alias-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,536 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,536 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,536 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.quicksight.describe-dashboard.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001315603CF10>
2022-12-06 08:25:24,537 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x00000131560A43A0>>
2022-12-06 08:25:24,537 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x00000131560A43D0>>
2022-12-06 08:25:24,537 - MainThread - botocore.hooks - DEBUG - Event calling-command.quicksight.describe-dashboard: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x00000131560A45B0>>
2022-12-06 08:25:24,538 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2022-12-06 08:25:24,538 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2022-12-06 08:25:24,538 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2022-12-06 08:25:24,538 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2022-12-06 08:25:24,538 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2022-12-06 08:25:24,540 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2022-12-06 08:25:24,541 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\endpoints.json
2022-12-06 08:25:24,546 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000013154760A60>
2022-12-06 08:25:24,584 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\quicksight\2018-04-01\endpoint-rule-set-1.json
2022-12-06 08:25:24,585 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\data\partitions.json
2022-12-06 08:25:24,586 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.quicksight: calling handler <function add_generate_presigned_url at 0x00000131546C5310>
2022-12-06 08:25:24,589 - MainThread - botocore.endpoint - DEBUG - Setting quicksight timeout as (60, 60)
2022-12-06 08:25:24,590 - MainThread - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Region': 'us-east-1', 'UseDualStack': False, 'UseFIPS': False}
2022-12-06 08:25:24,591 - MainThread - botocore.regions - DEBUG - Endpoint provider result: https://quicksight.us-east-1.amazonaws.com
2022-12-06 08:25:24,591 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.quicksight.DescribeDashboard: calling handler <function base64_decode_input_blobs at 0x0000013155FB5D30>
2022-12-06 08:25:24,591 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.quicksight.DescribeDashboard: calling handler <function generate_idempotent_uuid at 0x000001315477B9D0>
2022-12-06 08:25:24,592 - MainThread - botocore.hooks - DEBUG - Event before-call.quicksight.DescribeDashboard: calling handler <function inject_api_version_header_if_needed at 0x0000013154781280>
2022-12-06 08:25:24,592 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeDashboard) with params: {'url_path': '/accounts/223485597511/dashboards/data-transfer-cost-analysis-template', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.9.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off command/quicksight.describe-dashboard'}, 'body': b'', 'url': 'https://quicksight.us-east-1.amazonaws.com/accounts/223485597511/dashboards/data-transfer-cost-analysis-template', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x00000131569D40D0>, 'has_streaming_input': False, 'auth_type': None}}
2022-12-06 08:25:24,592 - MainThread - botocore.hooks - DEBUG - Event request-created.quicksight.DescribeDashboard: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x00000131569D41C0>>
2022-12-06 08:25:24,593 - MainThread - botocore.hooks - DEBUG - Event choose-signer.quicksight.DescribeDashboard: calling handler <function set_operation_specific_signer at 0x000001315477B8B0>
2022-12-06 08:25:24,593 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2022-12-06 08:25:24,593 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/accounts/223485597511/dashboards/data-transfer-cost-analysis-template

host:quicksight.us-east-1.amazonaws.com
x-amz-date:20221206T082524Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2022-12-06 08:25:24,594 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20221206T082524Z
20221206/us-east-1/quicksight/aws4_request
1a77942383ce0b62546c552744177661471b4ecb153a1c19ee5204008426d1eb
2022-12-06 08:25:24,594 - MainThread - botocore.auth - DEBUG - Signature:
b13a44d79b182a48a951bbc1feaf2c0ac97acf381f5ac4a7e47cdf638a7a1924
2022-12-06 08:25:24,594 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://quicksight.us-east-1.amazonaws.com/accounts/223485597511/dashboards/data-transfer-cost-analysis-template, headers={'User-Agent': b'aws-cli/2.9.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off command/quicksight.describe-dashboard', 'X-Amz-Date': b'20221206T082524Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AKIAABCDEFG123456789/20221206/us-east-1/quicksight/aws4_request, SignedHeaders=host;x-amz-date, Signature=b13a44d79b182a48a951bbc1feaf2c0ac97acf381f5ac4a7e47cdf638a7a1924'}>
2022-12-06 08:25:24,599 - MainThread - botocore.httpsession - DEBUG - Certificate path: C:\Program Files\Amazon\AWSCLIV2\awscli\botocore\cacert.pem
2022-12-06 08:25:24,599 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): quicksight.us-east-1.amazonaws.com:443
2022-12-06 08:25:25,263 - MainThread - urllib3.connectionpool - DEBUG - https://quicksight.us-east-1.amazonaws.com:443 "GET /accounts/223485597511/dashboards/data-transfer-cost-analysis-template HTTP/1.1" 403 300
2022-12-06 08:25:25,266 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 06 Dec 2022 08:25:25 GMT', 'Content-Type': 'application/json', 'Content-Length': '300', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'f7f88582-19bc-4adf-85ae-c2b9f1585812', 'x-amzn-ErrorType': 'AccessDeniedException'}
2022-12-06 08:25:25,268 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"Message":"User: arn:aws:iam::123456789012:user/my-username is not authorized to perform: quicksight:DescribeDashboard on resource: arn:aws:quicksight:us-east-1:223485597511:dashboard/data-transfer-cost-analysis-template because no resource-based policy allows the quicksight:DescribeDashboard action"}'
2022-12-06 08:25:25,274 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 06 Dec 2022 08:25:25 GMT', 'Content-Type': 'application/json', 'Content-Length': '300', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'f7f88582-19bc-4adf-85ae-c2b9f1585812', 'x-amzn-ErrorType': 'AccessDeniedException'}
2022-12-06 08:25:25,275 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"Message":"User: arn:aws:iam::123456789012:user/my-username is not authorized to perform: quicksight:DescribeDashboard on resource: arn:aws:quicksight:us-east-1:223485597511:dashboard/data-transfer-cost-analysis-template because no resource-based policy allows the quicksight:DescribeDashboard action"}'
2022-12-06 08:25:25,276 - MainThread - botocore.hooks - DEBUG - Event needs-retry.quicksight.DescribeDashboard: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x0000013156A195E0>>
2022-12-06 08:25:25,277 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2022-12-06 08:25:25,278 - MainThread - botocore.hooks - DEBUG - Event after-call.quicksight.DescribeDashboard: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x0000013156A190D0>>
2022-12-06 08:25:25,279 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 460, in main
  File "awscli\clidriver.py", line 595, in __call__
  File "awscli\clidriver.py", line 798, in __call__
  File "awscli\clidriver.py", line 929, in invoke
  File "awscli\clidriver.py", line 941, in _make_client_call
  File "awscli\botocore\client.py", line 341, in _api_call
  File "awscli\botocore\client.py", line 697, in _make_api_call
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the DescribeDashboard operation: User: arn:aws:iam::123456789012:user/my-username is not authorized to perform: quicksight:DescribeDashboard on resource: arn:aws:quicksight:us-east-1:223485597511:dashboard/data-transfer-cost-analysis-template because no resource-based policy allows the quicksight:DescribeDashboard action

An error occurred (AccessDeniedException) when calling the DescribeDashboard operation: User: arn:aws:iam::123456789012:user/my-username is not authorized to perform: quicksight:DescribeDashboard on resource: arn:aws:quicksight:us-east-1:223485597511:dashboard/data-transfer-cost-analysis-template because no resource-based policy allows the quicksight:DescribeDashboard action
```

It looks like a simple permissions issue for the dashboard template, but I wanted to give as much information as I could.

**Comment by iakov-aws** [comment]
Thanks for reporting this. Fixed in the latest release -> https://github.com/aws-samples/aws-cudos-framework-deployment/releases/tag/0.2.7

**Comment by robmoss2k** [comment]
Confirmed as fixed here. Thanks!
