### ISSUE TITLE
update Compute Optimizer Dashboard failed

### ISSUE THREAD

**Issue by holgerfeix** [aws-samples/aws-cudos-framework-deployment#592]
Hi Team, 
tried to update COD. Installed latest framework 0.2.23. It updates the datasets properly, but at compute_optimzer_all_options it fails. 
I have also other datasets / analysis and dashboards in my account. So far, this was never a problem. With the newer framework it tries to update the datasets, which is good. But it tries to update also datasets outside of CID, which will fail. 
Is there a way to solve this? Or do I need to remove all other Quicksight resources?
If you need more detailed logs, please let me know.

BR
```
? [view-compute-optimizer-lambda-lines-s3FolderPath] Required parameter: s3FolderPath (Compute Optimiser Lambda report S3 path): s3://skf.logging.costoptimizationdata571740337447/Compute_Optimizer/Compute_Optimizer_lambda
Updating table compute_optimizer_lambda_lines
Analysing view compute_optimizer_lambda_options
Analysing view compute_optimizer_all_options
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/bin/cid-cmd", line 8, in <module>
    sys.exit(main())
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 34, in wrapper
    res = func(ctx, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 194, in update
    ctx.obj.update(dashboard_id, force=force, recursive=recursive, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 164, in wrap
    return func(self, *args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 903, in update
    return self._deploy(dashboard_id, recursive=recursive, update=True)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 419, in _deploy
    self.create_datasets(required_datasets_names, dashboard_datasets, recursive=recursive, update=update)




[cloudshell-user@ip-10-4-4-239 ~]$ 
```

**Comment by iakov-aws** [comment]
Hello
The stacktrace looks like partial do you have full one? 
please can you retry with -vvv flag and provide resulting cid.log to cloud-intelligence-dashboards@amazon.com ?
