### ISSUE TITLE
Error when checking status of CAD dashboard with no cid_version

### ISSUE THREAD

**Issue by dnmll** [aws-samples/aws-cudos-framework-deployment#834]
When checking the status of Cost Anomaly Dashboard an error occurs. Looks to be due to cid_version not being set on the dashboard. This error prevents the rest of the feature from showing the options to refresh the datasets.
```
cid-cmd status --dashboard-id aws-cost-anomalies

Dashboard status:
  Id:        aws-cost-anomalies
  Name:      AWS Cost Anomalies
  Health:    healthy
  Status:    up to date
Traceback (most recent call last):
  File "/Users/dnmll/.pyenv/versions/3.11.8/bin/cid-cmd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cid/cli.py", line 35, in wrapper
    res = func(ctx, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cid/cli.py", line 173, in status
    ctx.obj.status(dashboard_id, **kwargs)
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cid/common.py", line 169, in wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cid/common.py", line 651, in status
    dashboard.display_status()
  File "/Users/dnmll/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cid/helpers/quicksight/dashboard.py", line 119, in display_status
    cid_version = self.deployedTemplate.cid_version
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cid_version'
```

**Comment by iakov-aws** [comment]
Will be in the next release

**Comment by iakov-aws** [comment]
This one was was fixed by @juchavw recently
